spring.application.name=WtcSync

# MongoDB
spring.data.mongodb.uri=mongodb+srv://vhisoares39_db_user:Nm8Z4si2FKUFLK7f@cluster0.wx4tjw1.mongodb.net/wtc_crm?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=WtcSyncSecretKeyParaTokenJWTQueDeveTer256BitsMinimo2026
jwt.expiration=86400000

server.forward-headers-strategy=framework
